### ISSUE TITLE
Handling of root elements

### ISSUE THREAD

**Issue by gapipro** [dbtedman/postcss-prefixwrap#158]
Maybe this is more of a question but I would say that root elements (html, body) are treated a bit incorrectly.

Current behaivour:

Source: 
```css
html {
 color: red;
}

body {
 color: blue;
}
```

Result:
```css
.wrap {
 color: red;
}

.wrap {
 color: blue;
}
```

Expected result:

```css
html {
 color: red;
}

.wrap body {
 color: blue;
}
```

or even: 
```css
html {
 color: red;
}

body {
 color: blue;
}
```

Why I think the output should be as follows is: html is the true root element and it cannot have a class on top of that. So yea `html` tag should be left as it is. But `body` can already be influenced by `html` tag.
